name: tests

on:
  push:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    env:
      COVERAGE_THRESHOLD: 85

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run PyCharm Security
        uses: tonybaloney/pycharm-security@master
        with:
          fail_on_warnings: no
      - name: Python Unit Tests
        run: |
          pip install pytest mock pytest-mock coverage;
          coverage run -m pytest;
          coverage report --fail-under=${COVERAGE_THRESHOLD}
